- name: Ensure .bash_logout clears history for every user
  hosts: all
  become: true
  tasks:
    - name: Get list of all users
      command: getent passwd
      register: passwd_output

    - name: Ensure .bash_logout file exists and has the required content
      copy:
        dest: "{{ item.home }}/.bash_logout"
        content: |
          # Clear the history
          history -c
          # Write the changes to the history file
          history -w
          # Remove the history file
          rm -f ~/.bash_history
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0644"
      with_items: "{{ users }}"
      when: item.home is match("^/home/")

  vars:
    users: "{{ passwd_output.stdout_lines | map('split', ':') | map('list', ['0', '5']) | map('combine', 'name', 'home') }}"
